### ISSUE TITLE
Support Value well known type

### ISSUE THREAD

**Issue by codebien** [grafana/xk6-grpc#55]
### Context

From the community we got a report regarding the missing support for [Value](https://protobuf.dev/reference/protobuf/google.protobuf/#value) Protobuf type: https://community.grafana.com/t/k6-is-sending-empty-text-for-datetime-string/105656.

An edited version of our [internal test for Any](https://github.com/grafana/k6/blob/d1d5969d0e8fcd3c3f7d8e38e7b7aa495143e507/js/modules/k6/grpc/client_test.go#L319) confirms the issue. Sharing the patch below.

[grpc-value-type-test.txt](https://github.com/grafana/xk6-grpc/files/12918537/grpc-value-type-test.txt)

**Comment by olegbespalov** [comment]
@codebien we do support (well actually we do after #49 ) this type, check this PR https://github.com/grafana/xk6-grpc/pull/56 

I belive we're missing more examples (maybe here, but for sure in k6-docs) of how to use these wrappers. It's not so transparent that in the case of the wrapper, there is no need to pack this into the structure, like: 

```javascript
let respString = client.invoke("grpc.wrappers.testing.Service/TestValue", "John")
if (respString.message !== "hey John") {
	throw new Error("expected to get 'hey John', but got a " + respString.message)
}

let respNumber = client.invoke("grpc.wrappers.testing.Service/TestValue", 12)
if (respNumber.message !== 42) {
	throw new Error("expected to get '42', but got a " + respNumber.message)
}
```

**Comment by codebien** [comment]
@olegbespalov I'm struggling to find some good references about it. Reading https://protobuf.dev/reference/protobuf/google.protobuf/#value I had the impression was the user suggested is a correct form. Do you have other references with better documentation?

**Comment by olegbespalov** [comment]
@codebien, the link that you've suggested is the right one. But keep in mind that this is the definition of the specification of the protobuf language. It's lacking of language-specific. 

For instance, there is no direct access to `string_value`. It's the responsibility of the serializer (in our case, it's https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) to put the correct value there, or at least it's what's happening for the most cases.
